# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cont_overlap_core <- function(N, Nsp, xis, xes, attributs, transectid, tol) {
    .Call('_coocfuncs_cont_overlap_core', PACKAGE = 'coocfuncs', N, Nsp, xis, xes, attributs, transectid, tol)
}

bin_data_core <- function(xis, xes, spp, bins, binsize) {
    .Call('_coocfuncs_bin_data_core', PACKAGE = 'coocfuncs', xis, xes, spp, bins, binsize)
}

sample_transect_core <- function(N, xis, xes, spp, groups, xmax, binsize) {
    .Call('_coocfuncs_sample_transect_core', PACKAGE = 'coocfuncs', N, xis, xes, spp, groups, xmax, binsize)
}

overlap <- function(xi_i, xi_j, xe_i, xe_j) {
    .Call('_coocfuncs_overlap', PACKAGE = 'coocfuncs', xi_i, xi_j, xe_i, xe_j)
}

overlap_binary <- function(istart, iend, jstart, jend) {
    .Call('_coocfuncs_overlap_binary', PACKAGE = 'coocfuncs', istart, iend, jstart, jend)
}

randp <- function() {
    .Call('_coocfuncs_randp', PACKAGE = 'coocfuncs')
}

shuffle_core <- function(xs, xmax) {
    .Call('_coocfuncs_shuffle_core', PACKAGE = 'coocfuncs', xs, xmax)
}

#'@export
get_cover <- function(xs, xmax) {
    .Call('_coocfuncs_get_cover', PACKAGE = 'coocfuncs', xs, xmax)
}

trans_cover <- function(xis, xes, xmax) {
    .Call('_coocfuncs_trans_cover', PACKAGE = 'coocfuncs', xis, xes, xmax)
}

